Repository sami2py/sami2py, pull requests merged in 2019-07, with the labels that each got.

#70 Unit Test upgrade and bugfix for unformatted files
  .coveragerc
  .github/pull_request_template.md
  .gitignore
  sami2py/_core.py
  sami2py/_core_class.py
  sami2py/tests/test_core.py
  sami2py/tests/test_core_class.py
  sami2py/tests/test_data/ref_f_sami2py-1.00.namelist
  sami2py/tests/test_data/ref_u_sami2py-1.00.namelist
  sami2py/tests/test_data/test/lon256/1999_257/deniu.dat
  sami2py/tests/test_data/test/lon256/1999_257/exb.inp
  sami2py/tests/test_data/test/lon256/1999_257/glatu.dat
  sami2py/tests/test_data/test/lon256/1999_257/glonu.dat
  sami2py/tests/test_data/test/lon256/1999_257/sami2py-1.00.namelist
  sami2py/tests/test_data/test/lon256/1999_257/teu.dat
  sami2py/tests/test_data/test/lon256/1999_257/time.dat
  sami2py/tests/test_data/test/lon256/1999_257/tiu.dat
  sami2py/tests/test_data/test/lon256/1999_257/vsiu.dat
  sami2py/tests/test_data/test/lon256/1999_257/zaltu.dat
  sami2py/tests/test_utils.py
  sami2py/utils.py
Labels: bug, testing

#73 expanduser path, PEP8
  sami2py/utils.py
Labels: bug

#75 Xarray and other upgrades
  .travis.yml
  README.md
  docs/installation.rst
  docs/sample_workflow.rst
  sami2py/__init__.py
  sami2py/_core.py
  sami2py/_core_class.py
  sami2py/fortran/exb.inp
  sami2py/fortran/sami2py-1.00.f
  sami2py/fortran/sami2py-1.00.namelist
  sami2py/tests/test_core.py
  sami2py/tests/test_data/test/lon256/1999_256/denif.dat
  sami2py/tests/test_data/test/lon256/1999_256/glatf.dat
  sami2py/tests/test_data/test/lon256/1999_256/glonf.dat
  sami2py/tests/test_data/test/lon256/1999_256/sami2py-1.00.namelist
  sami2py/tests/test_data/test/lon256/1999_256/tef.dat
  sami2py/tests/test_data/test/lon256/1999_256/tif.dat
  sami2py/tests/test_data/test/lon256/1999_256/time.dat
  sami2py/tests/test_data/test/lon256/1999_256/version.txt
  sami2py/tests/test_data/test/lon256/1999_256/vsif.dat
  sami2py/tests/test_data/test/lon256/1999_256/zaltf.dat
  sami2py/tests/test_data/test/lon256/1999_257/deniu.dat
  sami2py/tests/test_data/test/lon256/1999_257/dennu.dat
  sami2py/tests/test_data/test/lon256/1999_257/exb.inp
  sami2py/tests/test_data/test/lon256/1999_257/glatu.dat
  sami2py/tests/test_data/test/lon256/1999_257/glonu.dat
  sami2py/tests/test_data/test/lon256/1999_257/sami2py-1.00.namelist
  sami2py/tests/test_data/test/lon256/1999_257/teu.dat
  sami2py/tests/test_data/test/lon256/1999_257/time.dat
  sami2py/tests/test_data/test/lon256/1999_257/tiu.dat
  sami2py/tests/test_data/test/lon256/1999_257/u4u.dat
  sami2py/tests/test_data/test/lon256/1999_257/version.txt
  sami2py/tests/test_data/test/lon256/1999_257/vsiu.dat
  sami2py/tests/test_data/test/lon256/1999_257/zaltu.dat
  sami2py/tests/test_utils.py
  setup.cfg
  setup.py
Labels: documentation, enhancement

#76 Add changelog file
  .github/pull_request_template.md
  CHANGELOG.md
Labels: documentation

#78 Update index reference for plotting routine
  sami2py/_core_class.py
Labels: documentation

#80 Pytest, testing expansion for neutrals and plots
  .coveragerc
  .gitignore
  .travis.yml
  CHANGELOG.md
  CONTRIBUTING.md
  README.md
  sami2py/__init__.py
  sami2py/_core_class.py
  sami2py/fortran/sami2py-1.00.f
  sami2py/tests/__init__.py
  sami2py/tests/test_core.py
  sami2py/tests/test_core_class.py
  sami2py/tests/test_data/test/lon256/1999_256/dennf.dat
  sami2py/tests/test_data/test/lon256/1999_256/sami2py-1.00.namelist
  sami2py/tests/test_data/test/lon256/1999_256/u4f.dat
  sami2py/tests/test_data/test/lon256/1999_257/dennu.dat
  sami2py/tests/test_data/test/lon256/1999_257/u4u.dat
  sami2py/tests/test_utils.py
  sami2py/utils.py
  setup.cfg
Labels: testing
